source 'https://cdn.cocoapods.org'
platform :ios, '11.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'shared', :path => '../shared'
end
